### ISSUE TITLE
v argument 

### ISSUE THREAD

**Issue by kpapachr1** [fzao/interpn#1]
Thanks for the nice interpolation function! But I would like to ask if there is any option to increase the length of v argument?
Actually, I passed to this argument an array insted of vector and it worked, but up to size:
78*43*5*4*6*6*6= 14489280

if I increase one dimension by one, the function stop working.

Since, I am interested to expand the first dimension of the input function up to 89, 
I would like to ask if there is an option to increase the size of the argument v.

Thank you in advance for your answer!
Best,
kpapachr1

**Comment by fzao** [comment]
Hello kpapachr1,

I don't see what the problem could be. Can you send me the example to make it clearer?

Thanks

**Comment by kpapachr1** [comment]
Hello fzao, 

Thank you for your message!

I made the following example, trying to semulate my data, and it works!!

# my example 

n1 <- 89
n2 <- 43
n3 <- 5
n4 <- 4
n5 <- 6
n6 <- 6
n7 <- 6

x1 <- seq(1,89,1)
x2 <- c(seq(0,2,0.05),2.5, 3.0)
x3 <- seq(0.6, 1, 0.1)
x4 <- seq(200, 500, 100)
x5 <- seq(0.5, 3, 0.5)
x6 <- seq(0,2,0.4)
x7 <- seq(0.05,0.8,0.15)

v <- array(sample(seq(0,1000,0.001), n1*n2*n3*n4*n5*n6*n7, replace = T),dim = c(n1, n2, n3, n4, n5, n6, n7))

# query points
xq1 <- sample(seq(1,89,0.5), 100000, replace = T)
xq2 <- sample(seq(0,3,0.01), 100000, replace = T)
xq3 <- sample(seq(0.6,1,0.01), 100000, replace = T)
xq4 <- sample(seq(200,500,1), 100000, replace = T)
xq5 <- sample(seq(0.5,3,0.01), 100000, replace = T)
xq6 <- sample(seq(0,2,0.01), 100000, replace = T)
xq7 <- sample(seq(0.05,0.8,0.01), 100000, replace = T)

output <- interpn(outmode=3, v , x1, x2, x3, x4, x5, x6, x7, xq1 ,xq2, xq3, xq4, xq5, xq6, xq7)


It seems that the dimensions of v argument is not a problem, but the problem may be in my original data. 
I am posting the error that I am get, when I am using my original data:

NA/NaN/Inf in foreign function call (arg 2)

I am not getting this error, if I reduced the dimensions of v argument, that's why I supposed that it my be  a limit the size of the arguments.
I will go again through my data to find out the problem. 

Thank you!
kpapachr1
